### ISSUE TITLE
Unrecognized function or variable 'GetMeshData'

### ISSUE THREAD

**Issue by JosephJay95** [AntonSemechko/IsoCut#1]
Hi Anton.

I'm trying to compute contour lines of a field (z axis values of each vertex). I get this error with 'GetMeshData' function. Is this function included in your file? I couldn't find it.

Thank you for your time.
Joseph

**Comment by AntonSemechko** [comment]
Joseph, 'GetMeshData' is already part of this toolbox and is located in the  '.../IsoCut/Auxiliary folder. If Matlab is not seeing 'GetMeshData' it means that you have not added the subfolder 'IsoCut/Auxilary' to the Matlab path. You can find examples of how to do that here: https://www.mathworks.com/help/matlab/ref/addpath.html

**Comment by JosephJay95** [comment]
Thank you !
